import 'package:flutter/material.dart';

import '../../../core/theme/app_colors.dart';

/// Severity level of a system alert.
enum AlertSeverity {
  critical(
    label: 'Critical',
    color: AppColors.alertCritical,
    icon: Icons.error_rounded,
  ),
  warning(
    label: 'Warning',
    color: AppColors.alertWarning,
    icon: Icons.warning_rounded,
  ),
  info(
    label: 'Info',
    color: AppColors.alertInfo,
    icon: Icons.info_rounded,
  );

  const AlertSeverity({
    required this.label,
    required this.color,
    required this.icon,
  });

  final String label;
  final Color color;
  final IconData icon;

  static AlertSeverity fromString(String? value) {
    switch (value?.toLowerCase()) {
      case 'critical':
        return AlertSeverity.critical;
      case 'warning':
        return AlertSeverity.warning;
      case 'info':
      default:
        return AlertSeverity.info;
    }
  }
}

/// A system alert generated by threshold breaches or device heartbeat timeouts.
class SystemAlert {
  const SystemAlert({
    required this.id,
    required this.systemId,
    this.deviceId,
    required this.severity,
    required this.message,
    required this.isAcknowledged,
    this.acknowledgedBy,
    this.acknowledgedAt,
    required this.createdAt,
  });

  final String id;
  final String systemId;
  final String? deviceId;
  final AlertSeverity severity;
  final String message;
  final bool isAcknowledged;
  final String? acknowledgedBy;
  final DateTime? acknowledgedAt;
  final DateTime createdAt;

  factory SystemAlert.fromJson(Map<String, dynamic> json) {
    return SystemAlert(
      id: json['id'] as String,
      systemId: json['system_id'] as String,
      deviceId: json['device_id'] as String?,
      severity: AlertSeverity.fromString(json['severity'] as String?),
      message: json['message'] as String? ?? 'Alert triggered',
      isAcknowledged: json['is_acknowledged'] as bool? ?? false,
      acknowledgedBy: json['acknowledged_by'] as String?,
      acknowledgedAt: json['acknowledged_at'] != null
          ? DateTime.parse(json['acknowledged_at'] as String)
          : null,
      createdAt: json['created_at'] != null
          ? DateTime.parse(json['created_at'] as String)
          : DateTime.now(),
    );
  }

  SystemAlert copyWith({
    bool? isAcknowledged,
    String? acknowledgedBy,
    DateTime? acknowledgedAt,
  }) {
    return SystemAlert(
      id: id,
      systemId: systemId,
      deviceId: deviceId,
      severity: severity,
      message: message,
      isAcknowledged: isAcknowledged ?? this.isAcknowledged,
      acknowledgedBy: acknowledgedBy ?? this.acknowledgedBy,
      acknowledgedAt: acknowledgedAt ?? this.acknowledgedAt,
      createdAt: createdAt,
    );
  }
}
